Add Total Runtime to Output #459
OHDSI/Achilles pull request #505
Opened 2020-12-18 11:40 UTC by hongwonjun

I implemented it simply.
If you let me know what to modify, I will apply it.

2020-12-18 16:10 UTC, alondhe approved these changes

2020-12-18 16:11 UTC, alondhe requested changes
Can you change the variable names to match the OHDSI convention?
So totalStart and totalDelta.

2020-12-18 23:54 UTC, hongwonjun commented
I didn't think of that part. Thank you for the information.

2021-01-05 19:14 UTC, alondhe approved these changes

2021-01-05 19:22 UTC, merged